# ddu plugins
# Core plugins {{{
[[plugins]] # ddu.vim
repo = 'github.com/Shougo/ddu.vim'
# repo = 'Milly/ddu.vim'
# rev = 'source-stream'
depends = ['denops.vim', 'nvim-treesitter']
on_func = 'ddu#start'
hooks_file = '$HOOKS_DIR/ddu/hook.lua'

# }}}

# UI plugins {{{
[[plugins]] # ddu-ui-ff
repo = 'github.com/Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
hooks_file = '$HOOKS_DIR/ddu/ff.lua'

[[plugins]] # ddu-ui-filer
repo = 'github.com/Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
hooks_file = '$HOOKS_DIR/ddu/filer.lua'
# }}}

# Kind plugins {{{
[[plugins]] # ddu-kind-file
repo = 'github.com/Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]] # ddu-kind-word
repo = 'github.com/Shougo/ddu-kind-word'
on_source = 'ddu.vim'

# }}}

# Source plugins {{{
[[plugins]] # ddu-source-file
repo = 'github.com/Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-file_rec
repo = 'github.com/Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/Shougo/ddu-source-line'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-help
repo = 'github.com/matsui54/ddu-source-help'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/matsui54/ddu-source-file_external'
on_source = 'ddu.vim'

[[plugins]] # vim-readme-viewer
repo = 'github.com/4513ECHO/vim-readme-viewer'
on_cmd = ['ReadmeOpen', 'DppReadme']
on_source = 'ddu.vim'
lua_add = '''
vim.g['readme_viewer#plugin_manager'] = [[dpp.vim]]
'''

[[plugins]] # ddu-source-buffer
repo = 'github.com/shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-action
repo = 'github.com/Shougo/ddu-source-action'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-register
repo = 'github.com/Shougo/ddu-source-register'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-rg
repo = 'github.com/shun/ddu-source-rg'
on_source = 'ddu.vim'

[[plugins]] # ddu-source-mr
repo = 'github.com/kuuote/ddu-source-mr'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/matsui54/ddu-source-highlight'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/Shougo/ddu-source-path_history'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/kuuote/ddu-source-git_status'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/kuuote/ddu-source-git_diff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/kyoh86/ddu-source-git_branch'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/kyoh86/ddu-source-git_log'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/kyoh86/ddu-source-git_diff_tree'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/4513ECHO/ddu-source-ghq'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/uga-rosa/ddu-source-lsp'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/Shougo/ddu-source-dummy'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/yuki-yano/ddu-source-nvim-notify'
on_source = 'ddu.vim'

# }}}

# Filter plugins {{{
[[plugins]] # ddu-filter-matcher_substring
repo = 'github.com/Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]] # ddu-filter-matcher_hidden
repo = 'github.com/Shougo/ddu-filter-matcher_hidden'
on_source = 'ddu.vim'

[[plugins]] # ddu-filter-matcher_relative
repo = 'github.com/Shougo/ddu-filter-matcher_relative'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/kuuote/ddu-filter-fuse'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/uga-rosa/ddu-filter-converter_devicon'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/Milly/ddu-filter-merge'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/Milly/ddu-filter-kensaku'
depends = 'kensaku.vim'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/kyoh86/ddu-filter-converter_hl_dir'
on_source = 'ddu.vim'

[[plugins]]
repo = 'github.com/gamoutatsumi/ddu-filter-converter_relativepath'
on_source = 'ddu.vim'

# }}}

# Column plugins {{{
[[plugins]] # ddu-column-icon_filename
repo = 'github.com/ryota2357/ddu-column-icon_filename'
on_source = 'ddu.vim'

# }}}

# Other or plugins with multiple functions {{{
[[plugins]]
repo = 'github.com/yasunori0418/ddu-gh_project'
on_source = 'ddu.vim'
# }}}
