# Git plugins
[[plugins]] # gitsigns.nvim
repo = 'github.com/lewis6991/gitsigns.nvim'
on_event = ['CursorHold']
hooks_file = '$HOOKS_DIR/gitsigns.lua'

[[plugins]]
repo = 'github.com/lambdalisue/gin.vim'
depends = ['denops.vim']
on_cmd = ['Gin', 'GinBranch', 'GinCd', 'GinChaperon', 'GinDiff', 'GinLog', 'GinPatch', 'GinStatus']
hooks_file = '$HOOKS_DIR/gin.lua'
