---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.193.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: rossmacarthur/sheldon@0.7.4
- name: jdx/mise@v2024.6.3
- name: sharkdp/bat@v0.24.0
- name: cli/cli@v2.51.0
- name: jqlang/jq@jq-1.7.1
- name: BurntSushi/ripgrep@14.1.0
- name: x-motemen/ghq@v1.6.1
- name: oven-sh/bun@bun-v1.1.13
- name: dandavison/delta@0.17.0
- name: denoland/deno@v1.44.2
- name: sharkdp/fd@v10.1.0
- name: junegunn/fzf@0.53.0
- name: eza-community/eza@v0.18.18
- name: golang/go@go1.22.4
