daemonize = true
primary_threshold_ms = 5000
max_history = 50
synchronize_selection_with_clipboard = true
snippets = []

# File path for clip history.
# If this value is omitted, `clipcatd` will persist history in `$XDG_CACHE_HOME/clipcat/clipcatd-history`.
# history_file_path = "/home/<username>/.cache/clipcat/clipcatd-history"

# File path for the PID file.
# If this value is omitted, `clipcatd` will place the PID file in `$XDG_RUNTIME_DIR/clipcatd.pid`.
# pid_file = "/run/user/<user-id>/clipcatd.pid"

[log]
file_path = "$XDG_STATE_HOME/clipcat/clipcatd.log"
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"

[watcher]
enable_clipboard = true
enable_primary = true
enable_secondary = false
sensitive_mime_types = ["x-kde-passwordManagerHint"]
filter_text_min_length = 1
filter_text_max_length = 20000000
denied_text_regex_patterns = []
capture_image = true
filter_image_max_size = 5242880

[grpc]
enable_http = false
enable_local_socket = true
host = "127.0.0.1"
port = 45045
# Path for the Unix domain socket.
# If this value is omitted, `clipcatd` will place the socket in `$XDG_RUNTIME_DIR/clipcat/grpc.sock`.
# local_socket = "/run/user/<user-id>/clipcat/grpc.sock"

[dbus]
enable = true

[metrics]
enable = true
host = "127.0.0.1"
port = 45047

[desktop_notification]
enable = true
icon = "accessories-clipboard"
timeout_ms = 2000
long_plaintext_length = 2000
