# Server endpoint
# The `clipcat-menu` connects to the server via a Unix domain socket if `server_endpoint` is a file path, such as:
# "/run/user/<user-id>/clipcat/grpc.sock".
# It connects via HTTP if `server_endpoint` is a URL, like: "http://127.0.0.1:45045".
server_endpoint = "$XDG_RUNTIME_DIR/clipcat/grpc.sock"
finder = "rofi"
preview_length = 80

[rofi]
line_length = 100
menu_length = 10
menu_prompt = "Clipcat"
extra_arguments = []

[dmenu]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []

# [choose]
# line_length = 100
# menu_length = 30
# menu_prompt = "Clipcat"
# extra_arguments = []

[custom_finder]
program = "fzf"
args = []

[log]
file_path = "$XDG_STATE_HOME/clipcat/clipcat-menu.log"
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
