snippets:
  - name: git status
    keyword: gs
    snippet: git status --short --branch

  - name: git commit
    keyword: gc
    snippet: git commit

  - name: git commit --amend
    keyword: gcam
    snippet: git commit --amend

  - name: git commit --all
    keyword: gca
    snippet: git commit --all

  - name: git diff
    keyword: gd
    snippet: git diff

  - name: git diff --staged
    keyword: gds
    snippet: git diff --staged

  - name: git push
    keyword: gps
    snippet: git push

  - name: git pull
    keyword: gpl
    snippet: git pull

  - name: git pull --rebase
    keyword: gplr
    snippet: git pull --rebase

  - name: git lol
    keyword: gl
    snippet: git lol

completions:
  - name: change directory.
    patterns:
      - "^cd $"
    sourceCommand: "fd . --hidden --type d --exclude '.git' --color always"
    options:
      --prompt: "'Chdir> '"
      --preview: "cd {} && ls -a | sed '/^[.]*$/d'"

  - name: git staging
    patterns:
      - "^git (rm|add) $"
    sourceCommand: "fd . --hidden --type f --exclude '.git' --color always"
    options:
      --prompt: "'git staging> '"
      --preview: "bat {}"

  - name: mise plugins catalog
    patterns:
      - "^mise (plugins |)(i|install) $"
    sourceCommand: "mise plugins ls-remote"
    callback: "awk -F ' ' '{print $1}'"
    options:
      --prompt: "'mise plugins> '"

  - name: yay(pacman) packages catalog
    patterns:
      - "^yay -S(|y) $"
    sourceCommand: "yay -Ssq"
    options:
      --prompt: "'archlinux packages> '"
      --preview: "LANG=C yay -Si {}"

  - name: yay(pacman) packages remove
    patterns:
      - "^yay -Rs $"
    sourceCommand: "yay -Qsq"
    options:
      --prompt: "'archlinux packages> '"
      --preview: "LANG=C yay -Si {}"

  - name: yay(pacman) packages show infomation
    patterns:
      - "^yay -Si $"
    sourceCommand: "yay -Ssq"
    options:
      --prompt: "'archlinux packages> '"
      --preview: "LANG=C yay -Si {}"

  - name: gist edit
    patterns:
      - "^gh gist edit $"
    sourceCommand: "gh gist list"
    callback: "awk -F ' ' '{print $1}'"
    options:
      --prompt: "'gist> '"
      --preview: "gh gist view {}"

  - name: gist view
    patterns:
      - "^gh gist view $"
    sourceCommand: "gh gist list"
    callback: "awk -F ' ' '{print $1}'"
    options:
      --prompt: "'gist> '"
