# https://skanehira.github.io/blog/posts/20201116-vim-writing-articles/
version: 2
tools:
  markdown-textlint: &markdown-textlint
    lint-command: 'npx --no-install textlint -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m [%trror/%r]'
    root-markers:
      - .textlintrc
languages:
  markdown:
    - <<: *markdown-textlint
Copy
